# Generated by Django 2.2 on 2019-12-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigone', '0003_auto_20191211_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_image_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_image_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='image_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artigone.SecondaryImage'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artigone.PrimaryImage'),
        ),
    ]
