# Generated by Django 2.2 on 2019-12-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigone', '0005_auto_20191212_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_solution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
