# Generated by Django 2.2 on 2019-12-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigone', '0006_game_first_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='second_solution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
